// Mock ingestion source used for local dev, CI, and the seed script.
// Produces deterministic rows so unit tests against the deal score can share
// the same fixture as the seeded DB.

import type {
  IngestionPage,
  NormalizedProperty,
  PropertySource,
} from "./PropertySource";

const FIXTURES: NormalizedProperty[] = [
  {
    uplandId: "mock-sf-112",
    address: "112 Market St",
    city: "San Francisco",
    state: "CA",
    country: "US",
    neighborhood: "Financial District",
    price: 1200,
    mintPrice: 1000,
    yieldPerMonth: 5,
    forSale: true,
    owner: "0xabc",
    lat: 37.79,
    lng: -122.4,
    collection: null,
    hasStructure: true,
    structureType: "house",
    vehicles: [{ name: "Ford Model T", type: "vehicle", rarity: "common" }],
  },
  {
    uplandId: "mock-det-9",
    address: "9 Elm",
    city: "Detroit",
    state: "MI",
    country: "US",
    neighborhood: null,
    price: 300,
    mintPrice: 280,
    yieldPerMonth: 0.4,
    forSale: true,
    owner: "0xdef",
    lat: 42.33,
    lng: -83.05,
    collection: null,
    hasStructure: false,
    structureType: null,
    vehicles: [
      { name: "Chevy Corvette", type: "vehicle", rarity: "rare" },
      { name: "Ford Mustang", type: "vehicle", rarity: "rare" },
      { name: "Dodge Charger", type: "vehicle", rarity: "uncommon" },
    ],
  },
  {
    uplandId: "mock-ny-501",
    address: "501 Broadway",
    city: "New York",
    state: "NY",
    country: "US",
    neighborhood: "Soho",
    price: 8000,
    mintPrice: 2000,
    yieldPerMonth: 40,
    forSale: false,
    owner: "0x111",
    lat: 40.72,
    lng: -74.0,
    collection: null,
    hasStructure: true,
    structureType: "commercial",
    vehicles: [],
  },
  {
    uplandId: "mock-bk-82",
    address: "82 Park Ave",
    city: "Brooklyn",
    state: "NY",
    country: "US",
    neighborhood: "Park Slope",
    price: 450,
    mintPrice: 440,
    yieldPerMonth: 1.1,
    forSale: true,
    owner: "0x222",
    lat: 40.67,
    lng: -73.98,
    collection: null,
    hasStructure: false,
    structureType: null,
    vehicles: [],
  },
  {
    uplandId: "mock-oak-77",
    address: "77 Ocean",
    city: "Oakland",
    state: "CA",
    country: "US",
    neighborhood: "Jack London",
    price: 600,
    mintPrice: 600,
    yieldPerMonth: 0.2,
    forSale: false,
    owner: "0x333",
    lat: 37.8,
    lng: -122.28,
    collection: null,
    hasStructure: false,
    structureType: null,
    vehicles: [{ name: "Beach Buggy", type: "vehicle", rarity: "common" }],
  },
  // Additional mock rows for facet/pagination coverage.
  {
    uplandId: "mock-sf-45",
    address: "45 Mission St",
    city: "San Francisco",
    state: "CA",
    country: "US",
    neighborhood: "SoMa",
    price: 950,
    mintPrice: 900,
    yieldPerMonth: 2.1,
    forSale: true,
    owner: "0x444",
    lat: 37.78,
    lng: -122.41,
    collection: "Early Adopters",
    hasStructure: true,
    structureType: "apartment",
    vehicles: [],
  },
  {
    uplandId: "mock-chi-18",
    address: "18 Michigan Ave",
    city: "Chicago",
    state: "IL",
    country: "US",
    neighborhood: "The Loop",
    price: 700,
    mintPrice: 650,
    yieldPerMonth: 2.2,
    forSale: true,
    owner: "0x555",
    lat: 41.88,
    lng: -87.62,
    collection: null,
    hasStructure: true,
    structureType: "house",
    vehicles: [{ name: "Checker Cab", type: "vehicle", rarity: "common" }],
  },
  {
    uplandId: "mock-mia-3",
    address: "3 Ocean Dr",
    city: "Miami",
    state: "FL",
    country: "US",
    neighborhood: "South Beach",
    price: 1800,
    mintPrice: 1500,
    yieldPerMonth: 3.5,
    forSale: true,
    owner: "0x666",
    lat: 25.78,
    lng: -80.13,
    collection: null,
    hasStructure: true,
    structureType: "villa",
    vehicles: [{ name: "Yacht", type: "vehicle", rarity: "legendary" }],
  },
];

export class MockSource implements PropertySource {
  public readonly name = "mock";

  // eslint-disable-next-line require-yield
  async *pages(_opts: { maxPages?: number }): AsyncIterable<IngestionPage> {
    yield {
      items: FIXTURES,
      cursor: null,
    };
  }

  /** Exposes the fixtures for the seed script + unit tests. */
  static fixtures(): NormalizedProperty[] {
    return FIXTURES.map((f) => ({ ...f, vehicles: [...f.vehicles] }));
  }
}
