from __future__ import annotations

from datetime import datetime

from sqlalchemy import DateTime, Float, ForeignKey, Integer, Text
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import func

from app.db import Base


class TradeInsight(Base):
    """
    Stored trade insight for a specific Opportunity, typically generated by
    the AI trade insight engine.
    """

    __tablename__ = "trade_insights"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)

    opportunity_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("opportunities.id", ondelete="CASCADE"),
        index=True,
        nullable=False,
    )

    # Narrative description of how to approach entry (levels, conditions, sizing cues).
    entry_strategy: Mapped[str] = mapped_column(Text, nullable=False)

    # Optional numeric summary of the risk/reward ratio (e.g. 2.5 for ~2.5:1),
    # when the engine can infer one. Can be left null when only qualitative
    # guidance is available.
    risk_reward_ratio: Mapped[float | None] = mapped_column(Float, nullable=True)

    # Text description of key catalysts that could make the trade work or fail.
    catalysts: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Explanation of why the trade is or is not attractive from a risk,
    # liquidity, and signal quality perspective.
    confidence_reasoning: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

