"use client";

import { useEffect, useState } from "react";

import { getResearchReport } from "@/lib/api";
import type { Opportunity } from "@/lib/types";

type Props = {
  opportunity: Opportunity;
};

type ResearchReport = Awaited<ReturnType<typeof getResearchReport>>;

export function ResearchReport({ opportunity }: Props) {
  const [report, setReport] = useState<ResearchReport | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    async function load() {
      try {
        const data = await getResearchReport(opportunity.id);
        if (cancelled) return;
        setReport(data);
      } catch {
        if (!cancelled) {
          setError(
            "Unable to load the research report for this opportunity.",
          );
        }
      } finally {
        if (!cancelled) {
          setLoading(false);
        }
      }
    }

    void load();

    return () => {
      cancelled = true;
    };
  }, [opportunity.id]);

  if (loading) {
    return (
      <section className="rounded-xl border border-slate-800 bg-slate-950/70 p-4 text-xs text-slate-400">
        Having the research desk compile a full report on this opportunity…
      </section>
    );
  }

  if (error) {
    return (
      <section className="rounded-xl border border-rose-800/60 bg-rose-950/40 p-4 text-xs text-rose-100">
        {error}
      </section>
    );
  }

  if (!report) {
    return (
      <section className="rounded-xl border border-slate-800 bg-slate-950/70 p-4 text-xs text-slate-400">
        No research report has been generated for this opportunity yet.
      </section>
    );
  }

  return (
    <section className="rounded-xl border border-slate-800 bg-slate-950/80 p-4 text-xs text-slate-200">
      <h3 className="text-sm font-semibold text-slate-50">
        Research Report
      </h3>
      <p className="mt-1 text-[11px] text-slate-400">
        Long-form analysis generated by Block70&apos;s research engine. Use
        this as a structured starting point for deeper work, not as a final
        investment memo.
      </p>

      <article className="mt-3 space-y-3 whitespace-pre-line text-xs leading-relaxed">
        <div>
          <h4 className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">
            Project Overview
          </h4>
          <p className="mt-1 text-slate-200">{report.project_overview}</p>
        </div>

        <div>
          <h4 className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">
            Signal Analysis
          </h4>
          <p className="mt-1 text-slate-200">{report.signal_analysis}</p>
        </div>

        <div>
          <h4 className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">
            Risk Factors
          </h4>
          <p className="mt-1 text-slate-200">{report.risk_factors}</p>
        </div>

        <div>
          <h4 className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">
            Potential Upside
          </h4>
          <p className="mt-1 text-slate-200">{report.potential_upside}</p>
        </div>

        <div>
          <h4 className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">
            Market Narrative
          </h4>
          <p className="mt-1 text-slate-200">{report.market_narrative}</p>
        </div>
      </article>
    </section>
  );
}

