from __future__ import annotations

from typing import Dict

from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from app.db import get_db
from app.models import DailyBriefing


router = APIRouter(prefix="/api/v1/briefings", tags=["briefings"])


def _serialize_briefing(briefing: DailyBriefing) -> Dict:
    return {
        "id": briefing.id,
        "summary": briefing.summary,
        "top_opportunities": briefing.top_opportunities,
        "top_tokens": briefing.top_tokens,
        "radar_events": briefing.radar_events,
        "market_sentiment": briefing.market_sentiment,
        "created_at": briefing.created_at.isoformat(),
    }


@router.get("/latest")
def get_latest_daily_briefing(
    db: Session = Depends(get_db),
) -> Dict:
    """
    Return the most recent DailyBriefing generated by the AI briefing engine.
    When none exists, returns a stub so the frontend can render without error.
    """
    briefing = (
        db.query(DailyBriefing)
        .order_by(DailyBriefing.created_at.desc())
        .first()
    )
    if briefing is None:
        from datetime import datetime, timezone
        return {
            "id": 0,
            "summary": "",
            "top_opportunities": [],
            "top_tokens": [],
            "radar_events": [],
            "market_sentiment": None,
            "created_at": datetime.now(timezone.utc).isoformat(),
        }
    return _serialize_briefing(briefing)

